version: '2'
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 172.18.0.192/26
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
     - vpcbr
  kafka:
    image: zif4test.azurecr.io/kafka_mongo_sync
    ports:
      - "9092:9092"
      - "27017:27017"
    expose:
      - "9092"
    networks:
     - vpcbr
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.18.0.194
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      GROUP_ID: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/:/var/run/


